# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from tensorflow_federated.proto.v0 import executor_pb2 as tensorflow__federated_dot_proto_dot_v0_dot_executor__pb2


class ExecutorStub(object):
    """A service interface to be implemented by executors.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateValue = channel.unary_unary(
                '/tensorflow_federated.v0.Executor/CreateValue',
                request_serializer=tensorflow__federated_dot_proto_dot_v0_dot_executor__pb2.CreateValueRequest.SerializeToString,
                response_deserializer=tensorflow__federated_dot_proto_dot_v0_dot_executor__pb2.CreateValueResponse.FromString,
                )
        self.CreateCall = channel.unary_unary(
                '/tensorflow_federated.v0.Executor/CreateCall',
                request_serializer=tensorflow__federated_dot_proto_dot_v0_dot_executor__pb2.CreateCallRequest.SerializeToString,
                response_deserializer=tensorflow__federated_dot_proto_dot_v0_dot_executor__pb2.CreateCallResponse.FromString,
                )
        self.CreateStruct = channel.unary_unary(
                '/tensorflow_federated.v0.Executor/CreateStruct',
                request_serializer=tensorflow__federated_dot_proto_dot_v0_dot_executor__pb2.CreateStructRequest.SerializeToString,
                response_deserializer=tensorflow__federated_dot_proto_dot_v0_dot_executor__pb2.CreateStructResponse.FromString,
                )
        self.CreateSelection = channel.unary_unary(
                '/tensorflow_federated.v0.Executor/CreateSelection',
                request_serializer=tensorflow__federated_dot_proto_dot_v0_dot_executor__pb2.CreateSelectionRequest.SerializeToString,
                response_deserializer=tensorflow__federated_dot_proto_dot_v0_dot_executor__pb2.CreateSelectionResponse.FromString,
                )
        self.Compute = channel.unary_unary(
                '/tensorflow_federated.v0.Executor/Compute',
                request_serializer=tensorflow__federated_dot_proto_dot_v0_dot_executor__pb2.ComputeRequest.SerializeToString,
                response_deserializer=tensorflow__federated_dot_proto_dot_v0_dot_executor__pb2.ComputeResponse.FromString,
                )
        self.SetCardinalities = channel.unary_unary(
                '/tensorflow_federated.v0.Executor/SetCardinalities',
                request_serializer=tensorflow__federated_dot_proto_dot_v0_dot_executor__pb2.SetCardinalitiesRequest.SerializeToString,
                response_deserializer=tensorflow__federated_dot_proto_dot_v0_dot_executor__pb2.SetCardinalitiesResponse.FromString,
                )
        self.ClearExecutor = channel.unary_unary(
                '/tensorflow_federated.v0.Executor/ClearExecutor',
                request_serializer=tensorflow__federated_dot_proto_dot_v0_dot_executor__pb2.ClearExecutorRequest.SerializeToString,
                response_deserializer=tensorflow__federated_dot_proto_dot_v0_dot_executor__pb2.ClearExecutorResponse.FromString,
                )
        self.Dispose = channel.unary_unary(
                '/tensorflow_federated.v0.Executor/Dispose',
                request_serializer=tensorflow__federated_dot_proto_dot_v0_dot_executor__pb2.DisposeRequest.SerializeToString,
                response_deserializer=tensorflow__federated_dot_proto_dot_v0_dot_executor__pb2.DisposeResponse.FromString,
                )


class ExecutorServicer(object):
    """A service interface to be implemented by executors.
    """

    def CreateValue(self, request, context):
        """Creates a value in the executor and returns a reference to it that can be
        supplied as an argument to other methods.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCall(self, request, context):
        """Creates a call in the executor and returns a reference to the result.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateStruct(self, request, context):
        """Creates a struct of values in the executor and returns a reference to it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSelection(self, request, context):
        """Creates a selection from an executor value and returns a reference to it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Compute(self, request, context):
        """Causes a value in the executor to get computed, and sends back the result.
        WARNING: Unlike all other methods in this API, this may be a long-running
        call (it will block until the value becomes available).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCardinalities(self, request, context):
        """Configures executor to handle specified cardinalities.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearExecutor(self, request, context):
        """Clears executor state, resetting executor service.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Dispose(self, request, context):
        """TODO(b/134543154): Given that there is no support for asynchronous server
        processing in Python gRPC, long-running calls may be a problem. Revisit
        this and look for alternatives.

        Causes one or more values in the executor to get disposed of (no longer
        available for future calls).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExecutorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateValue': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateValue,
                    request_deserializer=tensorflow__federated_dot_proto_dot_v0_dot_executor__pb2.CreateValueRequest.FromString,
                    response_serializer=tensorflow__federated_dot_proto_dot_v0_dot_executor__pb2.CreateValueResponse.SerializeToString,
            ),
            'CreateCall': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCall,
                    request_deserializer=tensorflow__federated_dot_proto_dot_v0_dot_executor__pb2.CreateCallRequest.FromString,
                    response_serializer=tensorflow__federated_dot_proto_dot_v0_dot_executor__pb2.CreateCallResponse.SerializeToString,
            ),
            'CreateStruct': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateStruct,
                    request_deserializer=tensorflow__federated_dot_proto_dot_v0_dot_executor__pb2.CreateStructRequest.FromString,
                    response_serializer=tensorflow__federated_dot_proto_dot_v0_dot_executor__pb2.CreateStructResponse.SerializeToString,
            ),
            'CreateSelection': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSelection,
                    request_deserializer=tensorflow__federated_dot_proto_dot_v0_dot_executor__pb2.CreateSelectionRequest.FromString,
                    response_serializer=tensorflow__federated_dot_proto_dot_v0_dot_executor__pb2.CreateSelectionResponse.SerializeToString,
            ),
            'Compute': grpc.unary_unary_rpc_method_handler(
                    servicer.Compute,
                    request_deserializer=tensorflow__federated_dot_proto_dot_v0_dot_executor__pb2.ComputeRequest.FromString,
                    response_serializer=tensorflow__federated_dot_proto_dot_v0_dot_executor__pb2.ComputeResponse.SerializeToString,
            ),
            'SetCardinalities': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCardinalities,
                    request_deserializer=tensorflow__federated_dot_proto_dot_v0_dot_executor__pb2.SetCardinalitiesRequest.FromString,
                    response_serializer=tensorflow__federated_dot_proto_dot_v0_dot_executor__pb2.SetCardinalitiesResponse.SerializeToString,
            ),
            'ClearExecutor': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearExecutor,
                    request_deserializer=tensorflow__federated_dot_proto_dot_v0_dot_executor__pb2.ClearExecutorRequest.FromString,
                    response_serializer=tensorflow__federated_dot_proto_dot_v0_dot_executor__pb2.ClearExecutorResponse.SerializeToString,
            ),
            'Dispose': grpc.unary_unary_rpc_method_handler(
                    servicer.Dispose,
                    request_deserializer=tensorflow__federated_dot_proto_dot_v0_dot_executor__pb2.DisposeRequest.FromString,
                    response_serializer=tensorflow__federated_dot_proto_dot_v0_dot_executor__pb2.DisposeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tensorflow_federated.v0.Executor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Executor(object):
    """A service interface to be implemented by executors.
    """

    @staticmethod
    def CreateValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tensorflow_federated.v0.Executor/CreateValue',
            tensorflow__federated_dot_proto_dot_v0_dot_executor__pb2.CreateValueRequest.SerializeToString,
            tensorflow__federated_dot_proto_dot_v0_dot_executor__pb2.CreateValueResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tensorflow_federated.v0.Executor/CreateCall',
            tensorflow__federated_dot_proto_dot_v0_dot_executor__pb2.CreateCallRequest.SerializeToString,
            tensorflow__federated_dot_proto_dot_v0_dot_executor__pb2.CreateCallResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateStruct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tensorflow_federated.v0.Executor/CreateStruct',
            tensorflow__federated_dot_proto_dot_v0_dot_executor__pb2.CreateStructRequest.SerializeToString,
            tensorflow__federated_dot_proto_dot_v0_dot_executor__pb2.CreateStructResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateSelection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tensorflow_federated.v0.Executor/CreateSelection',
            tensorflow__federated_dot_proto_dot_v0_dot_executor__pb2.CreateSelectionRequest.SerializeToString,
            tensorflow__federated_dot_proto_dot_v0_dot_executor__pb2.CreateSelectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Compute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tensorflow_federated.v0.Executor/Compute',
            tensorflow__federated_dot_proto_dot_v0_dot_executor__pb2.ComputeRequest.SerializeToString,
            tensorflow__federated_dot_proto_dot_v0_dot_executor__pb2.ComputeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetCardinalities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tensorflow_federated.v0.Executor/SetCardinalities',
            tensorflow__federated_dot_proto_dot_v0_dot_executor__pb2.SetCardinalitiesRequest.SerializeToString,
            tensorflow__federated_dot_proto_dot_v0_dot_executor__pb2.SetCardinalitiesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ClearExecutor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tensorflow_federated.v0.Executor/ClearExecutor',
            tensorflow__federated_dot_proto_dot_v0_dot_executor__pb2.ClearExecutorRequest.SerializeToString,
            tensorflow__federated_dot_proto_dot_v0_dot_executor__pb2.ClearExecutorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Dispose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tensorflow_federated.v0.Executor/Dispose',
            tensorflow__federated_dot_proto_dot_v0_dot_executor__pb2.DisposeRequest.SerializeToString,
            tensorflow__federated_dot_proto_dot_v0_dot_executor__pb2.DisposeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
